config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs

  # Kutsuu metodia toggle_banned users-controllerissa
  resources :users do
    post 'toggle_banned'
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  # TÄMÄ KORVAA REST CRUDIN
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :memberships, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # HUOM resource (ts. vain 1 sessio kerrallaan) -- uusi sessio --> sessioN/new
  # CONTROLLER JA NÄKYMÄTIEDOSTOJEN NIMET SILTI SESSIONSSSSSSSSSS
  resource :session, only: [:new, :create, :destroy]


  # ROOT
  get('/', to: 'breweries#index')

  # Sessionhallintaa
  get('signup', to: 'users#new')
  get('signin', to: 'sessions#new')
  delete('signout', to: 'sessions#destroy') # Parempi käytänne kuin GET tässä

  # 3rd party API (Beermapping)
  # Paikkaa 2 alempaa GETiä - nyt reititys onnistuu muodossa place_path(place.id) ym id.
  resources :places, only: [:index, :show]

  # get('places', to: 'places#index')
  # get('places/:id', to: 'places#show')
  post('places', to: 'places#search')

  # REST Rating
  # GET
  # get('ratings', to: 'ratings#index')
  # get('ratings/new', to: 'ratings#new')
  # POST
  # post('ratings', to: 'ratings#create')

  #vaihtoehtoisesti - root 'breweries#index'
  # get 'kaljat', to: 'beers#index'

  get('beerlist', to: 'beers#list')
  get('brewerylist', to: 'breweries#list')
end

app/models/user.rb
class User < ApplicationRecord
  include RatingAverage # NYT voi hyödyntää average_rating - metodia, jos on mahdollista päästä käsiksi ratingeihin user.ratings - tavalla

  # User voi hyödyntää uusia metodeja (tässä salasanan autentikointi) https://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html
  has_secure_password
  
  validates :username, uniqueness: true, length: {minimum: 3, maximum: 30} # Tällä validoidaan uniikit käyttäjätunnukset, joiden minimipituus on 3
  validates :password, length: {minimum: 4}, format: { with: /^(?=.*[A-Z])(?=.*[0-9])/, :multiline => true } # Salasanan pituus väh. 4 merkkiä, sisältää vähintään yhden ison kirjaimen sekä vähintään yhden numeron

  # dependent - oliot poistetaan, jos niihin liittyvä käyttäjä poistetaan
  # dependent - oliot poistetaan, jos niihin liittyvä käyttäjä poistetaan
  # dependent - oliot poistetaan, jos niihin liittyvä käyttäjä poistetaan
  
  has_many :ratings, dependent: :destroy # Käyttäjällä voi olla monta arvostelua -- access by user.ratings.params
  has_many :beers, through: :ratings # Monesta-moneen-yhteys arvostelujen kautta oluihin
  
  has_many :memberships, dependent: :destroy # Käyttäjä voi liittyä moneen klubiin
  has_many :beer_clubs, through: :memberships

  def favorite_beer
    return nil if ratings.empty?
    user_ratings = ratings.sort_by{ |r| r.score }
    favourite_rating = user_ratings.last
    favourite_rating.beer # Implicit return
    # ratings.order(score: :desc).limit(1).first.beer # optimoitu versio
  end

  def self.top(n)
    sorted_by_rating_in_desc_order = User.all.sort_by{ |s| -(s.ratings.count || 0) }
    # palauta listalta parhaat n kappaletta
    # miten? ks. http://www.ruby-doc.org/core-2.5.1/Array.html
    sorted_by_rating_in_desc_order.take(n)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    # @users = User.all
    # @users = User.includes(:ratings).all
    @users = User.includes(:beers).all # Tämä itseasiassa tuottaa saman tuloksen kuin alempi ratkaisu (includes ratings, beers)
    # @users = User.includes(:ratings, :beers).all # Nyt tietokantahaku suoritetaan vain kerran (ratingseille ja beerseille yhdet siis). Muuten jokaista riviä kohti tehdään kokonaishaku (näkyy minirackprofileristä)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    return redirect_to(users_url, notice: 'You have no permission to edit this user.') if not @user == current_user
    respond_to do |format|
      if user_params[:username].nil? and @user.update(user_params) # Ehto käyttäjätietojen muuttamiselle on se, että :username - field on null (eli tätä haaraa ei suoriteta, jos POST-pyynnön mukana on kyseiseen kenttään liitettyä dataa)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    return redirect_to(users_url, notice: 'You have no permission to destroy this user.') if not @user == current_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
      reset_session # Kokeillaan tyhjentää olemassaoleva sessio? TOIMII!!
    end
  end

  def toggle_banned
    if (current_user.admin)
      user = User.find(params[:user_id])
      user.update_attribute :banned, (not user.banned)
      redirect_to(user)
    else
      redirect_to(breweries_path) # Estetään turha pelleily(?)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!-- Tämä näytetään vain, jos käyttäjää ei ole olemassa (ts. signup page) -->
<div class="form-border">
  <% if @user.new_record? %>
    <div class="form-group">
      <%= form.label :username %>
      <%= form.text_field :username, class: "form-control" %>
    </div>
  <%end%>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :confirm_password %>
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>
    <%= form.submit class: "btn btn-primary"%>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Change password for <%= @user.username %></h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th> rated beers </th>
      <th> total ratings </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.username, user %></td>
        <td><%= user.beers.size %></td>
        <td><%= user.ratings.size %></td>
        <td>
          <% if current_user and current_user.admin and user.banned %> <!-- laitoin ehtoon myös current_userin 1. ehdoksi, muuten herjaa taas nil, kun adminiä ei voi tarkistaa muuten... -->
            <span class="badge badge-danger">Banned</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<!-- add grid container div? -->

<div class="userIntro">
  <h2>
    <%= @user.username %>
    <% if @user.banned %>
      <span class="badge badge-info">banned</span>
    <% end %>
  </h2>

  <% if current_user && current_user.admin %>
    <hr>
    <!-- Laiska tyyli, laitetaan nyt tällä kertaa tänne -->
    <b style="margin-right: 50px">Mod options</b>
    <% if @user.banned %>
      <%= link_to "Unban", user_toggle_banned_path(@user.id), method: :post, class: "btn btn-primary btn-link" %>
    <% else %>
      <%= link_to "Ban", user_toggle_banned_path(@user.id), method: :post, class: "btn btn-danger" %>
    <% end %>
  <% end %>
  <hr>
</div>

<div class="memberships">
  <p>member of</p>
  <ul>
    <% @user.beer_clubs.each do |club| %>
      <li><%= link_to club.name, beer_club_path(club.id) %></li> <!-- HUOM CLUB - EI - CLUBS -->
    <% end %>
  </ul>
</div>

<div class="userRatings">
  <h3>
    ratings
  </h3>
<ul>
  <% @user.ratings.each do |rating| %>
    <li>
      <%= rating %>
      <% if @user == current_user %> <!-- TÄMÄ EI RIITÄ YKSINÄÄN, laitettiin myös destroy-metodille samanlainen ehto, jos joku yrittää kiertää konsolimuutoksilla tämän -->
        <%= link_to 'delete rating', rating_path(rating.id), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </li>
  <% end %>
</ul>
</div>

<% if @user == current_user %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', users_path %>