config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs

  # Kutsuu metodia toggle_banned users-controllerissa
  resources :users do
    post 'toggle_banned'
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  # TÄMÄ KORVAA REST CRUDIN
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :memberships, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # HUOM resource (ts. vain 1 sessio kerrallaan) -- uusi sessio --> sessioN/new
  # CONTROLLER JA NÄKYMÄTIEDOSTOJEN NIMET SILTI SESSIONSSSSSSSSSS
  resource :session, only: [:new, :create, :destroy]


  # ROOT
  get('/', to: 'breweries#index')

  # Sessionhallintaa
  get('signup', to: 'users#new')
  get('signin', to: 'sessions#new')
  delete('signout', to: 'sessions#destroy') # Parempi käytänne kuin GET tässä

  # 3rd party API (Beermapping)
  # Paikkaa 2 alempaa GETiä - nyt reititys onnistuu muodossa place_path(place.id) ym id.
  resources :places, only: [:index, :show]

  # get('places', to: 'places#index')
  # get('places/:id', to: 'places#show')
  post('places', to: 'places#search')

  # REST Rating
  # GET
  # get('ratings', to: 'ratings#index')
  # get('ratings/new', to: 'ratings#new')
  # POST
  # post('ratings', to: 'ratings#create')

  #vaihtoehtoisesti - root 'breweries#index'
  # get 'kaljat', to: 'beers#index'

  get('beerlist', to: 'beers#list')
  get('brewerylist', to: 'breweries#list')
end

app/models/style.rb
class Style < ApplicationRecord
  has_many :beers

  def rating_sum
    # b.average_rating palauttaa taulukon
    # eli pitäisi käytännössä tehdä beers_sum.first, muuten sama
    beers.map{|b| b.ratings_sum}.sum
  end

  def rating_count
    # Lasketaan kunkin oluen ratingmäärä
    beers.map{|b| b.ratings.count}.sum
  end

  def rating_avg
    return 0 if rating_count == 0
    avg = rating_sum / rating_count
    avg.round(1)
  end

  def self.top(n)
    sorted_by_rating_in_desc_order = Style.all.sort_by{ |s| -(s.rating_avg || 0) }
    # palauta listalta parhaat n kappaletta
    # miten? ks. http://www.ruby-doc.org/core-2.5.1/Array.html
    sorted_by_rating_in_desc_order.take(n)
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_admin_does_operation, only: [:destroy]

  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:beer_style)
    end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/styles/_form.html.erb
<%= form_with(model: style, local: true) do |form| %>
  <% if style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-border">
  <div class="form-group">
    <%= form.label :beer_style %>
    <%= form.text_field :beer_style, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing Style</h1>

<%= render 'form', style: @style %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<h1>Styles</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @styles.each do |style| %>
      <tr>
        <td><%= style.beer_style %></td>
        <td><%= link_to 'Show', style, class: "btn btn-link btn-sm" %></td>
        <td><%= link_to 'Edit', edit_style_path(style), class: "btn btn-link btn-sm" %></td>
        <td><%= link_to 'Destroy', style, class: 'btn btn-danger btn-link btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<h1>New Style</h1>

<%= render 'form', style: @style %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<p>
  <strong>Beer style:</strong>
  <%= @style.beer_style %>
</p>

<% if @style.beers %>
  <ul>
  <% @style.beers.each do |beer|%>
    <li>
      <%= link_to beer, beer_path(beer.id) %>
    </li>
    <% end %>
  </ul>
<% end %>

<%= edit_button_if_current_user(@style)%> |
<!-- <%= link_to 'Edit', edit_style_path(@style) %> | -->
<%= link_to 'Back', styles_path %>