config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs

  # Kutsuu metodia toggle_banned users-controllerissa
  resources :users do
    post 'toggle_banned'
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  # TÄMÄ KORVAA REST CRUDIN
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :memberships, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # HUOM resource (ts. vain 1 sessio kerrallaan) -- uusi sessio --> sessioN/new
  # CONTROLLER JA NÄKYMÄTIEDOSTOJEN NIMET SILTI SESSIONSSSSSSSSSS
  resource :session, only: [:new, :create, :destroy]


  # ROOT
  get('/', to: 'breweries#index')

  # Sessionhallintaa
  get('signup', to: 'users#new')
  get('signin', to: 'sessions#new')
  delete('signout', to: 'sessions#destroy') # Parempi käytänne kuin GET tässä

  # 3rd party API (Beermapping)
  # Paikkaa 2 alempaa GETiä - nyt reititys onnistuu muodossa place_path(place.id) ym id.
  resources :places, only: [:index, :show]

  # get('places', to: 'places#index')
  # get('places/:id', to: 'places#show')
  post('places', to: 'places#search')

  # REST Rating
  # GET
  # get('ratings', to: 'ratings#index')
  # get('ratings/new', to: 'ratings#new')
  # POST
  # post('ratings', to: 'ratings#create')

  #vaihtoehtoisesti - root 'breweries#index'
  # get 'kaljat', to: 'beers#index'

  get('beerlist', to: 'beers#list')
  get('brewerylist', to: 'breweries#list')
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage

  # https://apidock.com/rails/v2.3.8/ActiveModel/Validations/ClassMethods/validates_presence_of
  validates_presence_of :name
  validates :year, numericality: { greater_than_or_equal_to: 1040, only_integer: true }
  validates :year, numericality: { less_than_or_equal_to: -> (brewery) { Date.current.year }, only_integer: true }

  has_many :beers, dependent: :destroy # Panimoon liittyvät oluet poistetaan oluen poistamisessa (+ siihen liittyvät ratingit)
  has_many :ratings, through: :beers # Nyt myös panimo voi hyödyntää OMIEN OLUIDEN ratingeja (käytetään suoraan olut = Find_by(...) -> olut.ratings.count tms.)

  # Kontrollerit voivat hyödyntää näitä metodeja suoraan
  # sen sijaan, että kysely tehtäisiin siellä (+ DRY fix)
  # materiaalissa lukee allaoleva..
  # "modelin rooli on nimenomaan toimia abstraktiokerroksena muun sovelluksen ja tietokannan välillä."
  scope :active, -> {where active: true}
  scope :retired, -> {where active: [nil,false]}

  def self.top(n)
    sorted_by_rating_in_desc_order = Brewery.all.sort_by{ |b| -(b.average_rating || 0) }
    # palauta listalta parhaat n kappaletta
    # miten? ks. http://www.ruby-doc.org/core-2.5.1/Array.html
    sorted_by_rating_in_desc_order.take(n)
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_admin_does_operation, only: [:destroy]
  # before_action :authenticate, only: [:destroy] # SAMA KUIN before_filter, autentikointi suoritetaan VAIN silloin, kun kutsutaan destroy-metodia

  # GET /breweries
  # GET /breweries.json
  def index
    return if request.format.html? && fragment_exist?('brewerylist')

    @breweries = Brewery.all # Vaaditaan, jotta breweries.json - polku antaisi dataa
    # @active_breweries = Brewery.where(active: true)
    # @retired_breweries = Brewery.where(active: [nil, false])
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired
    # render :panimot -- renderöi tiedoston views/breweries/panimot.html.erb (jos sellainen siis olemassa)
    render :index # renderöi hakemistossa view/breweries olevan näkymätemplaten index.html.erb
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
    # Avataan kurssimateriaalin mukaisesti tämä auki (redundant)
    @brewery = Brewery.find(params[:id])
    render :show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    expire_fragment('brewerylist')

    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    expire_fragment('brewerylist')

    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    expire_fragment('brewerylist')

    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    expire_fragment('brewerylist')
    
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)
  
    new_status = brewery.active? ? "active" : "retired"
  
    redirect_to brewery, notice:"brewery activity status changed to #{new_status}"
  end

  # Javascriptiä varten
  def list
  end

  private # rubocop herjaa jos ei riviä ylä- ja alapuolella

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end

  # Luodaan autentikointi
  # def authenticate
  #   admin_accounts = { "anton" => "notna", "geir" => "rieg", "ravel" => "levar" }
  #   authenticate_or_request_with_http_basic do |username, password|
  #     # implicit return
  #     admin_accounts[username] == password # https://www.railstutorial.org/book/rails_flavored_ruby#sec-hashes_and_symbols miksi username eikä :username
  #   end
  # end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_with(model: brewery, local: true) do |form| %>
  <% if brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-border">
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :year %>
    <%= form.number_field :year, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= form.label :active %>
  <%= form.check_box :active %>
</div>
  <%= form.submit class: "btn btn-primary" %>
<% end %>
</div>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<% cache 'brewerylist', skip_digest: true do %>

<h2>Active</h2>

<p> Number of active breweries: <%= @active_breweries.count %> </p>

<table class="table table-hover">
  <thead>
    <tr>
    <th>Name</th>
    <th>Year</th>
    </tr>
  </thead>

  <tbody>
    <% @active_breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery, class: "btn btn-link btn-sm" %></td>
        <td><%= brewery.year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Retired</h2>

<p> Number of retired breweries: <%= @retired_breweries.count %> </p>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Year</th>
  </tr>
  </thead>

  <tbody>
  <% @retired_breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery, class: "btn btn-link btn-sm" %></td>
        <td><%= brewery.year %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<% end %>
<!-- beers_path, new_beer_path yms yleisesti käytössä railsin magian avulla?? -->
<!-- beers_path, new_beer_path yms yleisesti käytössä railsin magian avulla?? -->
<%= link_to 'New Brewery', new_brewery_path if current_user%> |
<%= link_to 'Beer List', beers_path %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="year">Founded</a> </th>
    <th> <a href="#" id="amount">Beer amount</a> </th>
    <th>Activity status</th>
  </tr>

</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/panimot.html.erb
<p>panimoita <%= @breweries.count %></p>

app/views/breweries/show.html.erb
<!-- yksittäisen panimon cachays -->
<% cache @brewery do %> 

<h2>
  <%= @brewery.name%>
  <% if not @brewery.active  %>
    <span class="badge badge-info">inactive</span>
  <% end %>
</h2>

<p>
  <i>Established in: <%= @brewery.year %></i>
</p>

<p>
  Current selection consists of <b><%= @brewery.beers.count %></b> beer(s)
</p>

<p>
  <% @brewery.beers.each do |beer| %>
  <%= link_to beer.name, beer_path(beer.id) %>
  <% end %>
</p>

<p>
  <% if @brewery.ratings.empty? %>
    Brewery does not have rated beers!
  <% else %>
    <%= round(@brewery.average_rating) %> average rating
  <% end %>
</p>

<% end %>
<!-- END yksittäisen panimon cachays -->

<!-- Tuo esiin consolitulostuksen <%= @brewery.beers.to_a %> -->

<!-- Seems like @brewery finds id implicitly -->
<%= link_to 'Edit', edit_brewery_path(@brewery) if current_user%> |
<%= link_to 'Back', breweries_path %> |
<%= link_to "Toggle activity", toggle_activity_brewery_path(@brewery.id), method: :post %>