config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs

  # Kutsuu metodia toggle_banned users-controllerissa
  resources :users do
    post 'toggle_banned'
  end

  resources :beers

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  # TÄMÄ KORVAA REST CRUDIN
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :memberships, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # HUOM resource (ts. vain 1 sessio kerrallaan) -- uusi sessio --> sessioN/new
  # CONTROLLER JA NÄKYMÄTIEDOSTOJEN NIMET SILTI SESSIONSSSSSSSSSS
  resource :session, only: [:new, :create, :destroy]


  # ROOT
  get('/', to: 'breweries#index')

  # Sessionhallintaa
  get('signup', to: 'users#new')
  get('signin', to: 'sessions#new')
  delete('signout', to: 'sessions#destroy') # Parempi käytänne kuin GET tässä

  # 3rd party API (Beermapping)
  # Paikkaa 2 alempaa GETiä - nyt reititys onnistuu muodossa place_path(place.id) ym id.
  resources :places, only: [:index, :show]

  # get('places', to: 'places#index')
  # get('places/:id', to: 'places#show')
  post('places', to: 'places#search')

  # REST Rating
  # GET
  # get('ratings', to: 'ratings#index')
  # get('ratings/new', to: 'ratings#new')
  # POST
  # post('ratings', to: 'ratings#create')

  #vaihtoehtoisesti - root 'breweries#index'
  # get 'kaljat', to: 'beers#index'

  get('beerlist', to: 'beers#list')
  get('brewerylist', to: 'breweries#list')
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!-- HUOM OMA STYLE MARGIN-BOTTOM LISÄTTY ALLAOLEVAAN NAV - KOMPONENTTIIN!!!!! -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin-bottom: 50px">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'breweries', breweries_path, { class: "nav-link" } %>
          </li>      
          <li class="nav-item">
            <%= link_to 'beers', beers_path, { class: "nav-link" } %>
          </li>     
          <li class="nav-item">
            <%= link_to 'styles', styles_path, { class: "nav-link" } %>
          </li>   
          <li class="nav-item">
            <%= link_to 'ratings', ratings_path, { class: "nav-link" } %>
          </li>       
          <li class="nav-item">
            <%= link_to 'users', users_path, { class: "nav-link" } %>
          </li>  
          <li class="nav-item">
            <%= link_to 'clubs', beer_clubs_path, { class: "nav-link" } %>
          </li>   
          <li class="nav-item">
            <%= link_to 'places', places_path, { class: "nav-link" } %>
          </li> 
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to 'my page', current_user, { class: "dropdown-item" } %>
                <%= link_to 'rate a beer ', new_rating_path, { class: "dropdown-item" } %>
                <%= link_to 'join a club ', new_membership_path, { class: "dropdown-item" } %>
                <div class="dropdown-divider"></div>
                <%= link_to 'signout', signout_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
           <!--<li class="nav-item">
              <%= link_to current_user.username, current_user, { class: "nav-link" } %>
            </li> 
            <li class="nav-item">
              <%= link_to 'rate a beer ', new_rating_path, { class: "nav-link" } %>
            </li>   
            <li class="nav-item">
              <%= link_to 'join a club ', new_membership_path, { class: "nav-link" } %>
            </li> 
            <li class="nav-item">
             Ilman method: :delete - muutosta bootcrap / jquery tulkitsee näitä linkkejä GET - muotoon?
              <%= link_to 'signout', signout_path, method: :delete, class: "nav-link" %>
            </li> -->                   
          <% else %>
            <li class="nav-item">
              <%= link_to 'signin', signin_path, { class: "nav-link" } %>
            </li>  
            <li class="nav-item">
              <%= link_to 'signup', signup_path, { class: "nav-link" } %>
            </li>                        
          <% end %>                            
        </ul>
      </div>
    </nav>

    <div class="container">
      <% if notice %>
      <div class="alert alert-primary top-margin" role="alert">
        <%= notice %>
      </div>
      <% end %>
      <div class="row">
        <div class="col-sm-8">
          <%= yield %>
        </div>
      <div class="col-sm-4">
        <img 
        src="http://www.cs.helsinki.fi/u/mluukkai/wadror/pint.jpg" 
        width="200"
        style="padding-top:30px"
        >
      </div>
    </div>
  </div>
  </body>
</html>